### ISSUE TITLE
Create the login screen for student

### ISSUE THREAD

**Issue by lakshyakalia** [roshansadath/CareerPaths-SOEN6011Summer2023#40]
#18 - Create the UI for login screen for student with all the required fields and buttons.

**Comment by Sindoora-Rao** [comment]
Commit References :

- https://github.com/roshansadath/CareerPaths-SOEN6011Summer2023/commit/9e174c23da01863c63ef5b0bceb4f95ba8463477

-  [8e748613c62db6298ba0e7babcb43a7ac0a76b43 ](https://github.com/roshansadath/CareerPaths-SOEN6011Summer2023/commit/3dde49b5542be22f0c905e04a14f602bc074280b) 
- https://github.com/roshansadath/CareerPaths-SOEN6011Summer2023/commit/f6c75210e0bfd3cb6aab2d1bda42ad7e8e33d47c
